Wasm32 support
arduano/simdeez pull request #66
Opened 2023-11-11 16:50 UTC by yzsolt

Adds support for WebAssembly SIMD, using the currently available stable intrinsics in Rust.

I also added a GitHub action for automated testing. Benchmarking also works, and shows a ~3x improvement of SIMD vs. scalar when running in `wasmtime`.

Note that I'm not a SIMD expert, so I may have missed some optimization opportunities when implementing operations which don't map 1:1 to WASM SIMD intrinsics. I've tried to follow already existing SSE and NEON implementations though.

Closes https://github.com/arduano/simdeez/issues/20.

2024-12-05 09:08 UTC, arduano requested changes

2024-12-05 09:08 UTC, arduano commented on src/tests/lib/tester.rs
> +        //elementwise_eq_tester_impl!(@full Scalar, $simd_ty, $simd_base, $simd_fn, $arg_cnt, $precision);
Please keep scalar uncommented

2024-12-15 06:17 UTC, arduano commented
Request my review when you think it's ready, also please mention how to run/test it

2024-12-15 08:24 UTC, yzsolt commented
Hey, I think it's ready! Rebased onto master and reenabled the commented out scalar tests.

About testing: I've set up things in a way that if you specify `wasm32-wasi` as target, `wasmtime` (de-facto standard Rust WebAssembly runtime) will be used for running the produced .wasm modules. It's installed on CI automatically, locally you have [to do it yourself](https://docs.wasmtime.dev/cli-install.html) beforehand. Both `cargo test` and `cargo bench` work for `wasm32-wasi`. `cargo bench` spits out some error logs (I think it's related to limited file access inside WebAssembly), but otherwise works.

For more complex testing you can build `simdnoise` for WebAssembly, which I did back when I initially implemented this. It worked nicely, got the same 2-3x scalar -> SIMD speedups in WASM as in native code.

2024-12-16 02:56 UTC, arduano approved these changes
Looks about right, I can't find any issues. Is it good to merge?

2024-12-16 09:52 UTC, yzsolt commented
> Looks about right, I can't find any issues. Is it good to merge?

Yes, ship it!

2024-12-17 09:47 UTC, merged